### ISSUE TITLE
Make functions that take `String` take `impl Into<String>`?

### ISSUE THREAD

**Issue by icefoxen** [garritfra/qbe-rs#14]
Just an idea I had while reading the example code.  Pretty much what it says on the tin.  If you like the idea I'll happily make a PR for it.

Pro's: Less typing `function.add_block("foo".into())`, more `function.add_block("foo")`

Con's: Probably a bit more compile time.

**Comment by garritfra** [comment]
Sounds like a reasonable change to me. I'd be happy to take your PR!
